# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('player_TS', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_PER', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_OBPM', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_DBPM', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_WS48', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_REBPCT', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_BLKPCT', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_3PTPCT', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_ASTPCT', models.DecimalField(decimal_places=3, max_digits=20)),
                ('player_STLPCT', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
