# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftmain', '0003_player_player_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_uuid',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
